In [6]:
import yfinance as yf
import matplotlib.pyplot as plt
from datetime import timedelta
import datetime

In [8]:
end_date = datetime.datetime.now()
start_date = end_date - timedelta(days=500)
df = yf.download(
            "MSFT",
            start=start_date,
            end=end_date,
            auto_adjust=True,
            progress=False,
)

In [9]:
df

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2024-01-23  394.422760  394.897383  389.508542  391.308121  20525900
2024-01-24  398.041687  401.077237  395.955384  397.033146  24867000
2024-01-25  400.325775  402.441770  398.012043  399.781960  21021200
2024-01-26  399.396332  401.611211  397.913168  399.831396  17803300
2024-01-29  405.121368  405.378460  399.791850  401.502444  24510200
...                ...         ...         ...         ...       ...
2025-05-30  460.359985  461.679993  455.540009  459.720001  34770500
2025-06-02  461.970001  462.109985  456.890015  457.140015  16626500
2025-06-03  462.970001  464.140015  460.859985  461.470001  15743800
2025-06-04  463.869995  465.690002  463.019989  464.000000  14162700
2025-06-05  467.679993  469.649994  464.029999  464.959991  20131700

[344 rows x 5 columns]